/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "on-background": "#ffffff",
        "inverse-on-surface": "#555555",
        "on-primary-fixed": "#004348",
        "on-error-container": "#ffa8a3",
        "on-secondary-fixed-variant": "#535a6b",
        "on-secondary-fixed": "#373d4e",
        "outline": "#757575",
        "background": "#080808",
        "error-container": "#9f0519",
        "surface-container-low": "#111111",
        "on-tertiary": "#002b5e",
        "error": "#ff716c",
        "primary-container": "#5eacb5",
        "surface-container-highest": "#222222",
        "on-tertiary-fixed": "#001738",
        "secondary-fixed-dim": "#cbd1e6",
        "on-primary-fixed-variant": "#006269",
        "tertiary-fixed-dim": "#6da3ff",
        "on-primary-container": "#00272b",
        "secondary-fixed": "#d9dff5",
        "surface-dim": "#080808",
        "primary-fixed-dim": "#8edbe4",
        "surface-variant": "#222222",
        "tertiary-dim": "#639dfd",
        "surface-tint": "#9ceaf2",
        "primary-dim": "#8edbe4",
        "on-surface-variant": "#ababab",
        "on-tertiary-fixed-variant": "#003876",
        "on-secondary-container": "#c9d0e5",
        "secondary-dim": "#cbd1e6",
        "secondary": "#d9dff5",
        "on-primary": "#00575e",
        "outline-variant": "#333333",
        "secondary-container": "#404758",
        "on-error": "#490006",
        "inverse-primary": "#046971",
        "surface": "#080808",
        "on-secondary": "#495061",
        "surface-bright": "#2c2c2c",
        "primary": "#9ceaf2",
        "on-surface": "#ffffff",
        "inverse-surface": "#f9f9f9",
        "tertiary-container": "#639dfd",
        "surface-container-high": "#1a1a1a",
        "surface-container-lowest": "#000000",
        "tertiary": "#7cabff",
        "on-tertiary-container": "#001f47",
        "error-dim": "#d7383b",
        "tertiary-fixed": "#86b1ff",
        "primary-fixed": "#9ceaf2",
        "surface-container": "#151515"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
